nx-squeezer/squeezer

packages/workspace/package.json, packages/workspace/schematics.json, packages/workspace/src/generators/codecov/generator.compat.ts, packages/workspace/src/generators/codecov/generator.spec.ts, packages/workspace/src/generators/contributors/generator.compat.ts, packages/workspace/src/generators/contributors/generator.spec.ts, packages/workspace/src/generators/eslint/generator.compat.ts, packages/workspace/src/generators/eslint/generator.spec.ts, packages/workspace/src/generators/github-workflow/generator.compat.ts, packages/workspace/src/generators/github-workflow/generator.spec.ts, packages/workspace/src/generators/prettier/generator.compat.ts, packages/workspace/src/generators/prettier/generator.spec.ts, packages/workspace/src/generators/renovate/generator.compat.ts, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/tsconfig/generator.compat.ts, packages/workspace/src/generators/tsconfig/generator.spec.ts
=> feat(workspace): ✨ provide schematics

default.json, packages/workspace/src/generators/core/renovate.ts, packages/workspace/src/generators/renovate/presets/default.json, packages/workspace/src/generators/renovate/presets/tooling.json, tooling.json
=> refactor(workspace): :recycle: simplify renovate preset for tooling

packages/workspace/package.json
=> chore(workspace): :package: add dependencies to package.json

SECURITY.md, packages/workspace-e2e/tests/workspace.spec.ts, packages/workspace/src/generators/lib/index.ts, packages/workspace/src/generators/lib/security/index.ts, packages/workspace/src/generators/lib/security/security.ts, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/renovate/generator.ts, packages/workspace/src/generators/renovate/security/SECURITY.md
=> feat(workspace): :sparkles: create security file with renovate (#68)

README.md, packages/workspace/src/generators/lib/readme/add-badge-to-readme.spec.ts, packages/workspace/src/generators/lib/readme/add-badge-to-readme.ts, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/renovate/generator.ts
=> feat(workspace): :sparkles: add renovate badge (#162)

.commitlintrc.json, .husky/commit-msg, package-lock.json, package.json, packages/workspace-e2e/tests/workspace.spec.ts, packages/workspace/README.md, packages/workspace/generators.json, packages/workspace/schematics.json, packages/workspace/src/generators/commitlint/README.md, packages/workspace/src/generators/commitlint/commitlint.ts, packages/workspace/src/generators/commitlint/generator.compat.ts, packages/workspace/src/generators/commitlint/generator.spec.ts, packages/workspace/src/generators/commitlint/generator.ts, packages/workspace/src/generators/commitlint/index.ts, packages/workspace/src/generators/commitlint/schema.json, packages/workspace/src/generators/commitlint/schema.ts, packages/workspace/src/generators/index.ts, packages/workspace/src/generators/lib/husky/husky.ts, packages/workspace/src/generators/lint-staged/README.md
=> feat(workspace): :sparkles: workspace generator to add commitlint (#62)

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml, package-lock.json, package.json, packages/workspace/package.json, packages/workspace/project.json
=> chore(workspace): :package: setup release target

.github/workflows/renovate.yml
=> ci(renovate): :chart_with_upwards_trend: run Renovate only on weekends

.github/renovate-config.js, nrwlWorkspace.json, packages/workspace/src/generators/renovate/files/.github/renovate-config.js__tmpl__, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/renovate/presets/nrwlWorkspace.json
=> fix(workspace): :bug: allow renovate migrations to fail

.github/workflows/renovate.yml, default.json, packages/workspace/src/generators/renovate/presets/default.json
=> feat(workspace): :sparkles: add stability days to renovate for npm updates

.github/renovate-config.js, nrwlWorkspace.json, packages/workspace/src/generators/renovate/files/.github/renovate-config.js__tmpl__, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/renovate/presets/nrwlWorkspace.json
Related to https://github.com/renovatebot/renovate/issues/7767#issuecomment-1367884733
=> fix(renovate): :bug: update command to run migrations

.github/renovate-config.js, nrwlWorkspace.json, nx-run-migrations.sh, package.json, packages/workspace/src/generators/renovate/files/.github/renovate-config.js__tmpl__, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/renovate/presets/nrwlWorkspace.json
Another try for https://github.com/nx-squeezer/squeezer/issues/251
Trying solution here https://github.com/renovatebot/renovate/issues/7767#issuecomment-745914692
=> fix(workspace): :bug: use bash script for renovate migrations

.vscode/launch.json, packages/workspace/src/generators/renovate/generator.ts
=> fix(workspace): :bug: solve runtime issue when adding renovate (#252)

packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/providers/provide-async.function.ts, tsconfig.base.json
=> feat(ng-async-injector): :sparkles: provide multiple injection tokens (#268)

packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/providers/provide-async.function.ts
=> feat(ng-async-injector): :sparkles: resolve all pending async injectors (#270)

packages/ng-async-injector/src/index.ts, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/interfaces/async-injection-token-type.ts, packages/ng-async-injector/src/lib/interfaces/async-provider-types.ts, packages/ng-async-injector/src/lib/providers/provide-async.function.ts
=> feat(ng-async-injector): :sparkles: resolve multiple tokens (#269)

packages/ng-async-injector/src/index.ts, packages/ng-async-injector/src/lib/directives/resolve-async-providers.directive.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/interfaces/async-class-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-factory-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-provider-config.ts, packages/ng-async-injector/src/lib/interfaces/async-static-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-value-provider.ts, packages/ng-async-injector/src/lib/interfaces/type-without-constructor-params.ts
=> feat(ng-async-injector): ✨ provide with useAsyncFactory and useAsyncClass options

packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts
=> feat(ng-async-injector): :sparkles: run async injectables in context

packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts
=> feat(ng-async-injector): :sparkles: detect cyclic dependencies (#313)

.vscode/settings.json, package-lock.json, package.json, packages/ng-async-injector-e2e/.eslintrc.json, packages/ng-async-injector-e2e/cypress.config.ts, packages/ng-async-injector-e2e/project.json, packages/ng-async-injector-e2e/src/e2e/app.cy.ts, packages/ng-async-injector-e2e/src/support/commands.ts, packages/ng-async-injector-e2e/src/support/e2e.ts, packages/ng-async-injector-e2e/tsconfig.json, workspace.json
=> test(ng-async-injector-e2e): :white_check_mark: add e2e tests for ng-async-injector using cypress

.vscode/extensions.json, .vscode/settings.json, packages/ng-async-injector/project.json, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts
=> feat(ng-async-injector): prevent declaring duplicated injection tokens

packages/workspace-e2e/tests/workspace.spec.ts, packages/workspace/src/generators/eslint/generator.spec.ts, packages/workspace/src/generators/eslint/generator.ts, packages/workspace/src/generators/eslint/index.ts, packages/workspace/src/generators/eslint/rules.ts, packages/workspace/src/generators/lib/git/get-git-repo.ts, packages/workspace/src/generators/lib/npm/get-npm-package-version.ts
=> refactor: :recycle: improve code quality for sonarcloud

.vscode/settings.json, packages/ng-async-injector-app/src/app/app.routes.ts, packages/ng-async-injector-app/src/app/async-providers/sixth.provider.ts, packages/ng-async-injector-app/src/app/async-tokens/sixth.token.ts, packages/ng-async-injector-app/src/app/child.component.ts, packages/ng-async-injector-e2e/src/e2e/app.cy.ts, packages/ng-async-injector-e2e/src/support/commands.ts, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/providers/provide-async.function.ts
=> feat(ng-async-injector): :sparkles: support hierarchical injectors

packages/ng-async-injector/src/lib/directives/resolve-async-providers.directive.spec.ts, packages/ng-async-injector/src/lib/directives/resolve-async-providers.directive.ts, packages/ng-async-injector/src/lib/functions/resolve-many.ts, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/interfaces/async-provider-types.ts, packages/ng-async-injector/src/lib/interfaces/injection-token-type.ts, packages/ng-async-injector/src/lib/providers/provide-async.function.ts, packages/ng-async-injector/src/lib/tokens/async-injector-initializer.token.ts, packages/ng-async-injector/src/lib/utils/calculate-circular-dependencies.function.spec.ts
=> feat(ng-async-injector): ✨ support providing injection tokens in component context (#308)

packages/ng-async-injector-app/src/app/async-providers/eighth.provider.ts, packages/ng-async-injector-app/src/app/async-tokens/eighth.token.ts, packages/ng-async-injector-app/src/app/child.component.ts, packages/ng-async-injector-app/src/app/route.component.ts, packages/ng-async-injector-e2e/src/e2e/app.cy.ts, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts
=> test(ng-async-injector-e2e): :white_check_mark: add e2e tests for component async provider

packages/ng-async-injector-app/src/app/app.routes.ts, packages/ng-async-injector-app/src/app/async-providers/multi.provider.ts, packages/ng-async-injector-app/src/app/async-tokens/multi-provider.token.ts, packages/ng-async-injector-app/src/app/route.component.ts, packages/ng-async-injector-e2e/src/e2e/app.cy.ts, packages/ng-async-injector/src/index.ts, packages/ng-async-injector/src/lib/functions/is-multi-provider.ts, packages/ng-async-injector/src/lib/injector/async-injector.spec.ts, packages/ng-async-injector/src/lib/injector/async-injector.ts, packages/ng-async-injector/src/lib/interfaces/array-item.ts, packages/ng-async-injector/src/lib/interfaces/async-class-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-factory-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-multi-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-static-provider.ts, packages/ng-async-injector/src/lib/interfaces/async-value-provider.ts
=> feat(ng-async-injector): ✨ support multi providers (#265)

.github/workflows/next.yml
Initial workflow to test next pipeline. TODO: optimize and parallelize
Closes #398
=> ci: :green_heart: new pipeline to early test next version

packages/workspace-e2e/tests/workspace.spec.ts, packages/workspace/project.json, packages/workspace/src/generators/lib/git/git-make-executable.spec.ts, packages/workspace/src/generators/lib/git/git-make-executable.ts, packages/workspace/src/generators/lib/git/index.ts, packages/workspace/src/generators/renovate/files/nx-create-migrations.sh, packages/workspace/src/generators/renovate/generator.spec.ts, packages/workspace/src/generators/renovate/generator.ts, packages/workspace/src/generators/renovate/make-migrations-script-executable-task.spec.ts, packages/workspace/src/generators/renovate/make-migrations-script-executable-task.ts, packages/workspace/src/generators/renovate/renovate.ts
=> feat(workspace): :sparkles: renovate adds create migrations script (#390)

.github/workflows/ci.yml, .github/workflows/next.yml, .github/workflows/release.yml, package.json, packages/ngx-async-injector/package.json, packages/workspace/package.json, packages/workspace/src/generators/github-workflow/files/ci.yml__tmpl__, packages/workspace/src/generators/github-workflow/generator.spec.ts
Closes #517
BREAKING CHANGE Update to node 18
=> feat: :arrow_up: update to node 18 and npm 9 (#517)

nx.json, packages/devkit-e2e/project.json, packages/devkit/jest.config.ts, packages/devkit/project.json, packages/ngx-async-injector-app/project.json, packages/ngx-async-injector-e2e/project.json, packages/ngx-async-injector/jest.config.ts, packages/ngx-async-injector/project.json, packages/workspace-e2e/project.json, packages/workspace/jest.config.ts, packages/workspace/project.json
=> chore: :recycle: simplify project configurations and use target defaults (#578)

.codecov.yml, .prettierignore, .vscode/settings.json, nx.json, packages/ngx-forms/.eslintrc.json, packages/ngx-forms/README.md, packages/ngx-forms/jest.config.ts, packages/ngx-forms/ng-package.json, packages/ngx-forms/package.json, packages/ngx-forms/project.json, packages/ngx-forms/src/index.ts, packages/ngx-forms/src/lib/functions/lazy-validator.spec.ts, packages/ngx-forms/src/lib/functions/lazy-validator.ts, packages/ngx-forms/src/lib/ngx-forms/ngx-forms.component.ts, packages/ngx-forms/src/lib/providers/index.ts, packages/ngx-forms/src/lib/providers/provide-lazy-validator.spec.ts, packages/ngx-forms/src/lib/providers/provide-lazy-validator.ts, packages/ngx-forms/src/lib/tokens/load-validator.token.ts, packages/ngx-forms/src/lib/types/load-validator-fn.ts, packages/ngx-forms/src/lib/validators/lazy-validator.ts, packages/ngx-forms/src/test-setup.ts, packages/ngx-forms/tsconfig.json, packages/ngx-forms/tsconfig.lib.json, packages/ngx-forms/tsconfig.lib.prod.json, packages/ngx-forms/tsconfig.spec.json, tsconfig.base.json
=> feat(ngx-forms): :tada: initial version (#374)

packages/utils/README.md
BREAKING CHANGE Release initial version
=> feat(utils): :sparkles: first stable version

package-lock.json, package.json
Reverts nx-squeezer/squeezer#1206
=> revert: upgrade to Angular 17.2-rc.0

package-lock.json
Automated changes by [Nx Migrate](https://github.com/nx-squeezer/squeezer/actions/workflows/migrate.yml) workflow.
=> chore: :arrow_up: migrate Nx workspace

packages/devkit/package.json, packages/workspace/package.json
Closes #1332
cc @roldengarm Thanks for catching this one!
=> feat: :arrow_up: widen range to support prettier v3
